### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by thomasgg** [dannyvankooten/vat.php#1]
Composer requires php >= 7.0 but documentation says it is supported by PHP 5.6+.
Haven't tested compatibility yet.

**Comment by dannyvankooten** [comment]
Hey @thomasgg, good catch. Library doesn't use any PHP7 specific feature and is compatible with PHP5.6, will update composer.json accordingly.

**Comment by dannyvankooten** [comment]
Closed by fe1b13bc3b39bc50934ee3e57f00460a2fe39013
