### ISSUE TITLE
"inEurope" is confusing

### ISSUE THREAD

**Issue by vyskoczilova** [dannyvankooten/vat.php#14]
Hi, I would suggest renaming the functions, your "$countries->inEurope()" lists countries in EU, not in Europe - I mean, Switzerland is in Europe but not in EU. It's bit confusing and the code is not easily readable. However, thanks for a great plugin!

**Comment by dannyvankooten** [comment]
Hi @vyskoczilova,

Good point, thanks for the heads up! I'm only seeing this issue now but if you (or anyone) have a PR for this that deprecates the old method name and introduces a better name, I'd happily accept it.
