### ISSUE TITLE
if a VAT does not exists in VIES it does not mean it does not exist

### ISSUE THREAD

**Issue by demobiel** [dannyvankooten/vat.php#18]
Just something I learned today, VIES only manages VAT numbers where the company has to pay VAT. For example Doctors or Libraries in Belgium don't have to pay VAT, but they have a VAT number. However you won't find those VAT numbers on VIES.

So I think the method name "validateExistence()" is not 100% accurate.

besides that: thanks for this library!

**Comment by dannyvankooten** [comment]
Hey, thanks for the heads-up @demobiel. I'm not entirely sure if that's something the library should account for too be honest.
