### ISSUE TITLE
Implement PSR-16 for the Cache interface

### ISSUE THREAD

**Issue by dannyvankooten** [dannyvankooten/vat.php#3]

**Comment by Jarlskov** [comment]
Was the plan with this just to replace the current cache interface with some interfaces following the PSR-16 standard, and then updating the NullCache to implement the new interface? In that case, I might jump on that if you'll accept a pull request.

**Comment by dannyvankooten** [comment]
Hi Jesper,

Yes, that was exactly the plan! A PR would be awesome but if not, I hope to get to this somewhere within the next few weeks. But any help would be very much appreciated.

Cheers!

On February 1, 2017 6:55:15 PM GMT+01:00, Jesper Jarlskov <notifications@github.com> wrote:
>Was the plan with this just to replace the current cache interface with
>some interfaces following the PSR-16 standard, and then updating the
>NullCache to implement the new interface? In that case, I might jump on
>that if you'll accept a pull request.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dannyvankooten/vat.php/issues/3#issuecomment-276730257

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Jarlskov** [comment]
Instead of doing what would essentially be a copy and paste of the interfaces, would it make sense to just add https://github.com/php-fig/simple-cache as a dependency, and implement the interface from that like a lot of other projects do (https://packagist.org/providers/psr/simple-cache-implementation) or would you rather not have that external dependency?

**Comment by dannyvankooten** [comment]
Yes definitely, that's the way I'd go about it too. Requiring the `psr/cache` repository as a Composer dependency, that is. The other method doesn't feel as DRY to me. :+1:

**Comment by Jarlskov** [comment]
psr/cache is the psr-6 cache. I've opted for psr/simple-cache which defines psr-16 which the issue title mentions. This interface is way simpler, and I believe it makes more sense for this case :-)
I've opened [a PR](https://github.com/dannyvankooten/vat.php/pull/6)

**Comment by dannyvankooten** [comment]
Closed by #6
